### ISSUE TITLE
如何对JSON 格式进行加密

### ISSUE THREAD

**Issue by ryan-che** [yinjihuan/monkey-api-encrypt#11]
现在没有对JSON 加密，对JSON 机密后也可以解密，但是报错json解析错误
JSON parse error: No content to map due to end-of-input; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input\n at [Source: UNKNOWN; line: 1, column: 0]

**Comment by yinjihuan** [comment]
json格式加密是什么意思啊，没看懂
