### ISSUE TITLE
我在maven的setting.xml里面配置了仓库，在pom文件里面加入，还是找不到

### ISSUE THREAD

**Issue by YangSimon** [yinjihuan/monkey-api-encrypt#13]
`	<repositories>
	<repository>
		 <id>jitpack.io</id>
		 <url>https://jitpack.io</url>
	</repository>
</repositories>`

`
        
        
        <dependency>
            <groupId>com.cxytiandi</groupId>
            <artifactId>spring-boot-starter-encrypt</artifactId>
            <version>1.0</version>
        </dependency>`

Dependency 'com.cxytiandi:spring-boot-starter-encrypt:1.0' not found less... (Ctrl+F1) 
Inspection info: Inspects a Maven model for resolution problems.

**Comment by yinjihuan** [comment]
你看下我的描述呀，maven仓库中的groupId跟源码中不一样：
```
<dependency>
    <groupId>com.github.yinjihuan</groupId>
    <artifactId>spring-boot-starter-encrypt</artifactId>
    <version>1.0</version>
</dependency>
```

**Comment by YangSimon** [comment]
<dependency>
            <groupId>com.cxytiandi</groupId>
            <artifactId>spring-boot-starter-encrypt</artifactId>
            <version>1.0.0</version>
        </dependency>

我在pom里面添加这个，一样也是找不到
Dependency 'com.cxytiandi:spring-boot-starter-encrypt:1.0.0' not found less... (Ctrl+F1) 
Inspection info: Inspects a Maven model for resolution problems.

**Comment by yinjihuan** [comment]
groupId是com.github.yinjihuan
