### ISSUE TITLE
关于rsa

### ISSUE THREAD

**Issue by naturalyui** [yinjihuan/monkey-api-encrypt#16]
您好，对于非对称加密的算法会生成一对公私钥，EncryptAlgorithm接口现在只支持传一个key，我现在的做法是扩展原有配置类的字段存放秘钥对，然后在EncryptAlgorithm的实现类中直接调用,这样接口中的第二个参数就可以去掉了

**Comment by yinjihuan** [comment]
这个是这样的，EncryptAlgorithm是配套内部内置的AES算法来用的，所以只需要传一个可以，对于rsa这种公钥私钥的可以参考我demo中的使用方式，既然自定义算法了，你只需要获取加解密的内容就行了，key那个参数可以不用，完全可以自己去获取公钥私钥的配置。
