### ISSUE TITLE
还是不能完全杜绝

### ISSUE THREAD

**Issue by rxxy** [yinjihuan/monkey-api-encrypt#17]
请求返回数据的加密，到客户端(浏览器)还是要解密，那就意味着解密算法是要放到浏览器上，这样别人完全可以拿到解密算法自己来进行数据的加解密，这个和混淆压缩等方式类似把，只能在一定程度上增加爬接口的难度，并不能完全避免呀

**Comment by yinjihuan** [comment]
对啊，我也没说完全能避免啊，没有任何绝对的事情，有的话爬虫就要失业了，但不一定是用在前后端啊，也有的是跟客户对接，双方都是后台服务这种的

**Comment by rxxy** [comment]
好的，说的也是。
