### ISSUE TITLE
使用文档过时了

### ISSUE THREAD

**Issue by DDERGOU** [yinjihuan/monkey-api-encrypt#28]
首先很感谢作者的开源，不过不得不说，[使用文档](https://github.com/yinjihuan/monkey-api-encrypt/wiki/使用文档)里的依赖中的加解密默认工具，解密使用的是默认系统默认编码，没有使用制定编码。最新的代码中是有修改这个问题的，想快速使用的时候没成功,还是要跟一下代码。

**Comment by yinjihuan** [comment]
默认加解密现在用的都是utf-8,我周六凌晨才更新的

**Comment by DDERGOU** [comment]
嗯（抱拳），我是上星期，也就是你更新前就拉了仓库下来用，不过现在直接用最新的源码编译放到本地仓库了。感谢。
