### ISSUE TITLE
多个ControllerAdvice会失效

### ISSUE THREAD

**Issue by mrdong916** [yinjihuan/monkey-api-encrypt#29]
使用@ControllerAdvice进行统一处理时，项目中有一个异常全局拦截也使用了@ControllerAdvice，异常拦截会失效

**Comment by yinjihuan** [comment]
不好意思，我没太明白什么意思？我这个框架中没有用到@ControllerAdvice啊

**Comment by mrdong916** [comment]
在这个路径下monkey-api-encrypt/spring-boot-starter-encrypt/src/main/java/com/cxytiandi/encrypt/advice/EncryptRequestBodyAdvice.java

**Comment by yinjihuan** [comment]
你的意思是你项目中也用到了，然后就冲突了对吧，这个包是最开始的1.0版本，基于Spring方式实现的。
你可以用最新的版本，代码是encrypt-core这个项目。使用文档：https://github.com/yinjihuan/monkey-api-encrypt/wiki/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3

**Comment by mrdong916** [comment]
已经解决了,并非冲突问题，是其他问题导致的
