### ISSUE TITLE
一点建议，增加@EncryptIgnore和@DecryptIgnore

### ISSUE THREAD

**Issue by echokk11** [yinjihuan/monkey-api-encrypt#33]
在全局开启加解密`debug=false`的情况下，需要局部排除一些比较麻烦，（比如swagger2），是否可增加如上注解以忽略加解密？

**Comment by yinjihuan** [comment]
可以加，但是看使用场景。一般我们认为加解密的基本上是核心接口，不会很多，因为毕竟加解密也是会损失性能的。
所以采用的方式是标记要加解密的接口。
如果要支持忽略的话，也就是说你的应用场景中90%要加解密，只有个别不需要加解密，你想通过忽略的方式来减少注解的使用

**Comment by yinjihuan** [comment]
是否需要加这个功能？在你的使用场景中确实存在我说的问题么

**Comment by echokk11** [comment]
你能加一下最好了，有这种场景，比如我需要全开加密，但是swagger和一些简单的接口我不需要加密。按照现有的配置就很麻烦

**Comment by yinjihuan** [comment]
行，我抽时间加下，其实就两种场景，一种就是按需配置加解密的接口，一种就是忽略加解密的接口，两者选其一

**Comment by yinjihuan** [comment]
加好了，版本是1.1.13

**Comment by yinjihuan** [comment]
![image](https://user-images.githubusercontent.com/17271895/57922179-b3b51d80-78d1-11e9-9758-324cea1c6f14.png)

**Comment by echokk11** [comment]
非常感谢
