### ISSUE TITLE
Required request body is missing

### ISSUE THREAD

**Issue by creatn** [yinjihuan/monkey-api-encrypt#35]
作者你好，遇到一个问题，在将解密后的字符串放到request中时：reqestWrapper.setRequestData(decyptRequestData);
在controller层遇到了Required request body is missing的问题，导致无法接收到正确参数。
我是参考实现，是我对什么地方没有处理导致的么？

**Comment by creatn** [comment]
不好意思，是我自己request传错了

**Comment by yinjihuan** [comment]
你可以直接用我打好的包呀
