### ISSUE TITLE
集成加密启动报SolrClient错误

### ISSUE THREAD

**Issue by wanghuan888** [yinjihuan/monkey-api-encrypt#37]
你好，我集成@EnableEncrypt //启用加密Starter 的时候，原本我使用了solrj，在启动类中加了@SpringBootApplication(exclude = SolrAutoConfiguration.class)这个注解，在新增了@EnableEncrypt 之后我的项目启动的时候报如下错（不加@EnableEncrypt之前项目正常运行）：
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'solrClient' defined in class path resource [org/springframework/boot/autoconfigure/solr/SolrAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.solr.client.solrj.SolrClient]: Factory method 'solrClient' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/solr/client/solrj/impl/HttpSolrClient$Builder

**Comment by yinjihuan** [comment]
这个应该是某个jar冲突了，你看下maven依赖
