### ISSUE TITLE
加上了加解密的注解不起作用

### ISSUE THREAD

**Issue by sanchiqingfeng** [yinjihuan/monkey-api-encrypt#38]
Springboot中加上了加解密的注解但是好像没有起作用，filter里面直接就跳过了加解密的过程

**Comment by sanchiqingfeng** [comment]
嗯发现了这个bug。。。我的项目访问是根路径的话，加上注解的路径，加在解密列表里时，会变成post://login，于是就匹配不上post:/login，就注解不起作用了，苦笑不得

**Comment by yinjihuan** [comment]
能提供简单的示列么？你的访问是根路径这个没太明白，比如你登陆，那么肯定是xxx.com/login, 前面多了一个斜杠是怎么来的？
