### ISSUE TITLE
解密的注解Decrypt可以标识强制解密吗？

### ISSUE THREAD

**Issue by aoyouxingkong** [yinjihuan/monkey-api-encrypt#4]
1、在测试接口的时候，没有对请求参数进行加密，依然可以请求和响应，建议加上属性，可以标识是否强制界面
2、注解的位置可以放到请求参数那块吗？类似@RequestBody一样，改成@Target(ElementType.PARAMETER)一样的

**Comment by yinjihuan** [comment]
1. 请求参数我在文章中也有说明，没做加密，目前只是对请求体方式加密了，也就是你说的@RequestBody方式，请求参数可以用签名的方式来防止篡改，这个我下周会写一篇文章，如果对参数安全性要求特别高，建议用post请求。

2. 注解的位置可以调整的，但这个不是什么大问题，放在方法上我那边获取的时候比较方便些。

**Comment by aoyouxingkong** [comment]
1.使用的是post请求方式，只是后端获取的请求参数，没有加密，可以正常的访问，可以提供下属性，标识是否强制解密，如果解密失败，直接返回异常
2.注解的位置调整，可以提高代码的可读性。
`Test test = new Test();
		Method[] methods = test.getClass().getMethods();
		for(Method m : methods){
			Parameter[] parameters = m.getParameters();
			for(Parameter p : parameters){
				Param param = p.getAnnotation(Param.class);
				if(param != null){
					System.out.println("name:" + param.name());
				}
			}
		}`
