### ISSUE TITLE
spring-boot-starter-encrypt这个包是你自己写的吗？ 我在maven仓库找不到这个包，收到请回复，谢谢！

### ISSUE THREAD

**Issue by wangxuegang** [yinjihuan/monkey-api-encrypt#40]

**Comment by godtrack** [comment]
这不有那个工程吗，动动手不能自己打包？

**Comment by yinjihuan** [comment]
我发的是jitpack这个仓库，文档都有写：https://github.com/yinjihuan/monkey-api-encrypt/wiki/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3。可以自己打包的。
