### ISSUE TITLE
关于两个/问题以及自动解密@RequestParam参数无值解决方法

### ISSUE THREAD

**Issue by Tubackup** [yinjihuan/monkey-api-encrypt#45]
最进用到了你的项目，发现自动解密@RequestParam参数无值，然后尝试自己手动添加，由于是引得第三方依赖，为了减少耦合，已提交自己github仓库中，希望能参考下
关于两个/的问题
是自己的项目中配置了
server.servlet.context-path=/
就会显示两个/
[项目地址](https://github.com/Tubackup/monkey-api-encrypt)

**Comment by Tubackup** [comment]
自动解密@RequestParam参数 只支持json格式的

**Comment by yinjihuan** [comment]
多谢反馈，context-path=/会在下个版本加进去。 @RequestParam 加密这个你们会用么？之前没做是因为这个场景的应用度不是很高，加密的参数最好还是放请求体内，放url中就需要考虑长度等问题

**Comment by yinjihuan** [comment]
1.2版本增加了单个 @RequestParam的解密支持，你的json格式的我没加进来，建议json格式还是用请求体。
