### ISSUE TITLE
使用graphql如何加密

### ISSUE THREAD

**Issue by rxxy** [yinjihuan/monkey-api-encrypt#5]
是否可以修改下加密范围，使得使用graphql的servlet时也可以加密数据

**Comment by yinjihuan** [comment]
graphql我没用过，如果它底层用的servlet的话也是可以做的，比较麻烦点而已

**Comment by rxxy** [comment]
好吧

**Comment by yinjihuan** [comment]
graphql如果用的servlet的话，目前应该可以支持了，请查看最新版本

**Comment by rxxy** [comment]
好的，应该可以了
