### ISSUE TITLE
关于注解配置忽略url加密解密，yml配置不在生效问题

### ISSUE THREAD

**Issue by dawnFlyme** [yinjihuan/monkey-api-encrypt#58]
![image](https://user-images.githubusercontent.com/20439037/81630518-6d3cc500-9438-11ea-945f-bb56f0f6ac30.png)
这一块配置的url，有没有可能将其合并。
比如我项目中使用swagger，这种其实需要在yml中配置比较合适。
不然我想到的只能再写一个Contr加注解配置了

**Comment by yinjihuan** [comment]
没太明白你的点，现在也可以在配置文件中配置忽略哪些接口，不知道你是否要的是这个

**Comment by dawnFlyme** [comment]
我的意思是加注解配置忽略后，文件配置忽略哪些接口就会失效。
上面的截图是获取忽略url list，上图中getRequestDecyptUriIgnoreList()方法中你先判断了ApiEncryptDataInit.requestDecyptUriIgnoreList.size()中有没有数据，有数据则返回。但这个数据是通过注解加载来的。this.requestDecyptUriIgnoreList;则是加载配置文件中的忽略的url。所以我想说的是注解的配置优先级会大于配置文件。
但是实际场景可能都会用到，就比如swagger的请求路径其实不需要用注解配置。
不知道有没有阐述清楚 感谢

**Comment by yinjihuan** [comment]
明白了，之前的想法是只有一种方式的配置，要么注解，要么配置文件，如果有注解就优先。后面可以考虑合并

**Comment by yinjihuan** [comment]
合并了配置 https://github.com/yinjihuan/monkey-api-encrypt/releases/tag/1.2.1.RELEASE
