### ISSUE TITLE
使用@RequestMapping时，如果没有指定method，则会报错！

### ISSUE THREAD

**Issue by lzyforever** [yinjihuan/monkey-api-encrypt#59]
在源码ApiEncryptDataInit类中处理requestMapping注解时，见下面源码：
        } else if (null != requestMapping) {
            RequestMethod m = requestMapping.method()[0];
            methodType = m.name().toLowerCase() + ":";
            uri.append(formatUri(requestMapping.value()[0]));
        }

直接取的requestMapping.method()[0]，此时会取不到请求的method，将会报数组越界！请fixed! 嘿嘿

**Comment by yinjihuan** [comment]
已修复 https://github.com/yinjihuan/monkey-api-encrypt/releases/tag/1.2.1.RELEASE

**Comment by lzyforever** [comment]
> 已修复 https://github.com/yinjihuan/monkey-api-encrypt/releases/tag/1.2.1.RELEASE

good job! 666
