### ISSUE TITLE
请支持一下get请求

### ISSUE THREAD

**Issue by jackBaozz** [yinjihuan/monkey-api-encrypt#6]
对get的请求加密支持请问有时间表吗？

**Comment by yinjihuan** [comment]
您指的是get的参数加密？

**Comment by jackBaozz** [comment]
是的，虽然一般默认get请求都是明文，但有些需求是虽然是get但还是要加密的。暂时是自己处理了get加密，但感觉还是不是很好。

**Comment by yinjihuan** [comment]
这种不是很好处理啊，要么每个参数都加密，要么所有参数都加密，但是涉及到一个问题，就是后端接收问题，然后解析，比如后端是2个参数，前端统一加密成一个参数，这样url映射本身就有问题了

**Comment by jackBaozz** [comment]
这种，暂时我的处理方式是，所有的 name=a&age=1 都加密为 sign=XXXXXXXX , 接收方有过滤器来进行解密还原为name=a&age=1 。这种方式处理post提交，放requestbody里面的就没法子了，request的body里面不能写入。这问题困扰好久。
