### ISSUE TITLE
随机生成key

### ISSUE THREAD

**Issue by csvf** [yinjihuan/monkey-api-encrypt#68]
您好，如果不用固定的key,需要随机生成aes加密key 是重写EncryptionConfig这个类就可以吗

**Comment by yinjihuan** [comment]
对的，加密的Key是从这个类获取的，或者完全自定义加密算法，自己控制就行

**Comment by csvf** [comment]
> 对的，加密的Key是从这个类获取的，或者完全自定义加密算法，自己控制就行

嗯，已经使用了 谢谢。
