### ISSUE TITLE
更新到1.2.2.RELEASE版本，访问controller报错Invalid AES key length: 8 bytes

### ISSUE THREAD

**Issue by lianyuLJ** [yinjihuan/monkey-api-encrypt#75]
在一个controller使用了@Encrypt注解，一访问就报错AES encrypt error和Invalid AES key length: 8 bytes，在yml配置了spring.encrypt.key = abcdef0123456789 使用1.2.RELEASE版本就没问题，但是我需要Restful风格API加解密，请问有办法解决吗

**Comment by lianyuLJ** [comment]
问题解决了，是我key的位数不够，1.2.RELEASE版本key用16位， 1.2.2.RELEASE的key用32位

**Comment by Caoam** [comment]
> 问题解决了，是我的key的一个词性，1.2.RELEASE版本key用16位，1.2.2.RELEASE的key用32位

你好，请问你是用的vue吗
